version: '3.8'

services:
  nginx:
    image: nginx:1.24
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - php
  
  php:
    image: php:8.3-fpm
    volumes:
      - ./app:/var/www/html
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: anh100700@
      MYSQL_DATABASE: project-one
      MYSQL_USER: anhcanh
      MYSQL_PASSWORD: Anh100700@
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: